# These are static & non-secret properties.
# Secrets should go in the .ENV example file and loaded there.

# App
ozs.app.version = 1.0.1

# Quarkus
quarkus.http.port = 3000
quarkus.log.level=INFO
quarkus.vertx.caching=false
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:4200,https://openzoosim.com,https://www.openzoosim.com

# DB
quarkus.datasource.db-kind = postgresql