-- ############################
-- OpenZooSim Official Schema
--
-- https://openzoosim.com
--
-- Licensed Under GNU GPLv3.
-- Copyright 2025. OpenZooSim. All Rights Reserved.
-- ############################

-- AUTH

CREATE TABLE IF NOT EXISTS "user_types" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMP DEFAULT (NOW()),
  "modified_at" TIMESTAMP,
  "is_archived" BOOLEAN DEFAULT false,
  "name" TEXT NOT NULL,
  "key" TEXT UNIQUE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_user_types_key ON "user_types" ("key");

CREATE TABLE IF NOT EXISTS "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMP DEFAULT (NOW()),
  "modified_at" TIMESTAMP,
  "is_archived" BOOLEAN DEFAULT false,
  "email" TEXT UNIQUE NOT NULL,
  "display_name" TEXT NOT NULL,
  "avatar_url" TEXT,
  "profile_text" TEXT,
  "is_verified" BOOLEAN DEFAULT false,
  "user_type_id" INTEGER,
  "password_hash" TEXT,
  "last_login" TIMESTAMP,
  "is_banned" BOOLEAN DEFAULT false,
  "ban_reason" TEXT,
  "can_use_api_keys" BOOLEAN DEFAULT false
);

ALTER TABLE "users" ADD FOREIGN KEY ("user_type_id") REFERENCES "user_types" ("id");

CREATE INDEX IF NOT EXISTS idx_users_email ON "users" ("email");

CREATE TABLE IF NOT EXISTS "user_login_history" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMP DEFAULT (NOW()),
  "modified_at" TIMESTAMP,
  "is_archived" BOOLEAN DEFAULT false,
  "user_id" INTEGER
);

ALTER TABLE "user_login_history" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

-- // USER TYPES
INSERT INTO public.user_types (name, key)
VALUES ('Admin', 'admin')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.user_types (name, key)
VALUES ('Free User', 'free')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.user_types (name, key)
VALUES ('Pro User', 'pro')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.user_types (name, key)
VALUES ('System', 'system')
ON CONFLICT (id) DO NOTHING;

-- // USERS
INSERT INTO public.users (email, display_name, user_type_id)
VALUES ('snowlynxsoftware+admin@gmail.com', 'MorpheusZero', 1)
ON CONFLICT (id) DO NOTHING;