--liquibase formatted sql

-- ChangeSet morpheuszero:20241102_001_create_users_table
-- This creates initial tables with essential fields

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,       -- Auto-incrementing ID
    username VARCHAR(255) NOT NULL, -- Username column (unique constraint can be added)
    email VARCHAR(255) NOT NULL UNIQUE,    -- Email column (unique constraint can be added)
    email_verified BOOLEAN DEFAULT FALSE, -- Email verification status
    password VARCHAR(255) NOT NULL, -- Hashed password for authentication
    role VARCHAR(20) DEFAULT 'FREE', -- Role of the user (default is 'FREE')
    is_api_user BOOLEAN DEFAULT FALSE, -- Flag to identify API users
    api_key VARCHAR(255), -- API key for API users
    last_login TIMESTAMP DEFAULT NULL,  -- Timestamp when the user last logged in
    last_api_access TIMESTAMP DEFAULT NULL, -- Timestamp when the user last accessed the API
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- Timestamp when the record is created
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  -- Timestamp when the record is updated
);

CREATE TABLE settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,       -- Auto-incrementing ID
    is_email_enabled BOOLEAN DEFAULT TRUE, -- Flag to enable/disable email notifications
    is_maintenance_mode BOOLEAN DEFAULT FALSE, -- Flag to enable/disable maintenance mode
    maintenance_message VARCHAR(255), -- Message to display when in maintenance mode
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- Timestamp when the record is created
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  -- Timestamp when the record is updated
);

INSERT INTO settings (maintenance_message) 
VALUES ('App is down for scheduled maintenance. Please try again later and check our socials for more info!');

CREATE TABLE user_login_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,       -- Auto-incrementing ID
    user_id BIGINT NOT NULL, -- User ID of the user who logged in
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- Timestamp when the record is created
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  -- Timestamp when the record is updated
);

ALTER TABLE user_login_history 
ADD CONSTRAINT fk_loginhistory_user_id 
FOREIGN KEY (user_id) REFERENCES users(id);
--changelog end