-- ############################
-- OpenZooSim Official Schema
--
-- https://openzoosim.com
--
-- Licensed Under GNU GPLv3.
-- Copyright 2024. OpenZooSim. All Rights Reserved.
-- 
-- This will allow you to create a new (empty) 
-- database from scratch to get started 
-- with OpenZooSim. This creates the most current
-- version of the schema (without any migrations).
-- ############################

-- AUTH

CREATE TABLE IF NOT EXISTS "banned_ips" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp DEFAULT (now()),
  "modified_at" timestamp,
  "is_archived" boolean DEFAULT false,
  "ip" text UNIQUE NOT NULL,
  "description" text
);

CREATE TABLE IF NOT EXISTS "user_types" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp DEFAULT (now()),
  "modified_at" timestamp,
  "is_archived" boolean DEFAULT false,
  "name" text NOT NULL,
  "key" text UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp DEFAULT (now()),
  "modified_at" timestamp,
  "is_archived" bool DEFAULT false,
  "email" text UNIQUE NOT NULL,
  "username" text NOT NULL,
  "is_verified" boolean DEFAULT false,
  "user_type_id" integer,
  "password_hash" text,
  "last_login" timestamp,
  "failed_login_attempts" integer DEFAULT 0,
  "is_banned" boolean DEFAULT false,
  "ban_reason" text,
  "can_use_api_keys" boolean DEFAULT false
);

ALTER TABLE "users" ADD FOREIGN KEY ("user_type_id") REFERENCES "user_types" ("id");

CREATE TABLE IF NOT EXISTS "user_login_history" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp DEFAULT (now()),
  "modified_at" timestamp,
  "is_archived" boolean DEFAULT false,
  "user_id" integer
);

ALTER TABLE "user_login_history" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

CREATE TABLE IF NOT EXISTS "user_sessions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp DEFAULT (now()),
  "modified_at" timestamp,
  "is_archived" bool DEFAULT false,
  "user_id" INTEGER,
  "ip" text NOT NULL,
  "device_thumbprint" text NOT NULL,
  "session_token" text NOT NULL,
  "expires_at" timestamp
);

ALTER TABLE "user_sessions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

CREATE TABLE IF NOT EXISTS "user_password_resets" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp DEFAULT (now()),
  "modified_at" timestamp,
  "is_archived" boolean DEFAULT false,
  "user_id" INTEGER,
  "token" text UNIQUE NOT NULL,
  "expires_at" timestamp
);

ALTER TABLE "user_password_resets" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

CREATE TABLE IF NOT EXISTS "user_api_keys" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp DEFAULT (now()),
  "modified_at" timestamp,
  "is_archived" boolean DEFAULT false,
  "user_id" integer,
  "api_key" text UNIQUE NOT NULL
);

ALTER TABLE "user_api_keys" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

--  METADATA

CREATE TABLE IF NOT EXISTS "shards" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp DEFAULT (now()),
  "modified_at" timestamp,
  "is_archived" bool DEFAULT false,
  "is_live" bool DEFAULT false,  
  "name" text NOT NULL,
  "description" text NOT NULL
);

CREATE TABLE IF NOT EXISTS "zoos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp DEFAULT (now()),
  "modified_at" timestamp,
  "is_archived" bool DEFAULT false, 
  "name" text NOT NULL,
  "description" text NOT NULL,
  "current_money" REAL NOT NULL DEFAULT 25000,
  "max_capacity" INTEGER NOT NULL DEFAULT 10,
  "owner_id" integer NOT NULL,
  "shard_id" integer NOT NULL
);

ALTER TABLE "zoos" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id");
ALTER TABLE "zoos" ADD FOREIGN KEY ("shard_id") REFERENCES "shards" ("id");

CREATE TABLE IF NOT EXISTS "animal_conservation_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp DEFAULT (now()),
  "modified_at" timestamp,
  "is_archived" bool DEFAULT false,
  "name" text NOT NULL,
  "description" text NOT NULL
);

CREATE TABLE IF NOT EXISTS "animal_regions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp DEFAULT (now()),
  "modified_at" timestamp,
  "is_archived" bool DEFAULT false,
  "name" text NOT NULL,
  "description" text NOT NULL
);

CREATE TABLE IF NOT EXISTS "animal_category" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp DEFAULT (now()),
  "modified_at" timestamp,
  "is_archived" bool DEFAULT false,
  "name" text NOT NULL,
  "description" text NOT NULL
);

-- ANIMALS

CREATE TABLE IF NOT EXISTS "animals" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp DEFAULT (now()),
  "modified_at" timestamp,
  "is_archived" bool DEFAULT false,
  "name" text NOT NULL,
  "description" text NOT NULL,
  "unique_key" text UNIQUE NOT NULL,
  "animal_category_id" integer NOT NULL,
  "animal_region_id" integer NOT NULL,
  "animal_conservation_status_id" integer NOT NULL,
  "image_url" text,
  "is_protected" bool DEFAULT false,
  "base_market_chance" REAL NOT NULL,
  "base_hype_factor" REAL NOT NULL,
  "base_market_cost" REAL NOT NULL,
  "base_fertility_factor" REAL NOT NULL,
  "base_health_factor" REAL NOT NULL,
  "base_happiness_threshold" REAL NOT NULL,
  "shard_id" integer NOT NULL
);

ALTER TABLE "animals" ADD FOREIGN KEY ("shard_id") REFERENCES "shards" ("id");
ALTER TABLE "animals" ADD FOREIGN KEY ("animal_category_id") REFERENCES "animal_category" ("id");
ALTER TABLE "animals" ADD FOREIGN KEY ("animal_region_id") REFERENCES "animal_regions" ("id");
ALTER TABLE "animals" ADD FOREIGN KEY ("animal_conservation_status_id") REFERENCES "animal_conservation_status" ("id");

CREATE TABLE IF NOT EXISTS "animal_instance" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp DEFAULT (now()),
  "modified_at" timestamp,
  "is_archived" bool DEFAULT false,
  "friendly_name" text,
  "animal_id" integer NOT NULL,
  "current_owner_id" integer,
  "original_owner_id" integer,
  "is_male" bool DEFAULT true,
  "is_locked" bool DEFAULT true,
  "add_hype_factor" REAL NOT NULL,
  "add_fertility_factor" REAL NOT NULL, 
  "add_health_factor" REAL NOT NULL,
  "current_happiness" REAL NOT NULL,
  "date_of_birth" timestamp NOT NULL,
  "shard_id" integer NOT NULL,
  "zoo_id" integer  
);

ALTER TABLE "animal_instance" ADD FOREIGN KEY ("shard_id") REFERENCES "shards" ("id");
ALTER TABLE "animal_instance" ADD FOREIGN KEY ("animal_id") REFERENCES "animals" ("id");
ALTER TABLE "animal_instance" ADD FOREIGN KEY ("current_owner_id") REFERENCES "users" ("id");
ALTER TABLE "animal_instance" ADD FOREIGN KEY ("original_owner_id") REFERENCES "users" ("id");
ALTER TABLE "animal_instance" ADD FOREIGN KEY ("zoo_id") REFERENCES "zoos" ("id");

CREATE TABLE IF NOT EXISTS "market_animals" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp DEFAULT (now()),
  "modified_at" timestamp,
  "is_archived" bool DEFAULT false,
  "is_system_listing" bool DEFAULT false,  
  "animal_instance_id" integer NOT NULL,
  "lister_id" integer,
  "buyer_id" integer,
  "price" REAL NOT NULL,
  "expires" timestamp NOT NULL,
  "shard_id" integer NOT NULL
);

ALTER TABLE "market_animals" ADD FOREIGN KEY ("shard_id") REFERENCES "shards" ("id");
ALTER TABLE "market_animals" ADD FOREIGN KEY ("animal_instance_id") REFERENCES "animal_instance" ("id");
ALTER TABLE "market_animals" ADD FOREIGN KEY ("lister_id") REFERENCES "users" ("id");
ALTER TABLE "market_animals" ADD FOREIGN KEY ("buyer_id") REFERENCES "users" ("id");

CREATE TABLE IF NOT EXISTS "market_global_settings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp DEFAULT (now()),
  "modified_at" timestamp,
  "is_archived" bool DEFAULT false,
  "listing_fee_percentage" REAL NOT NULL,
  "shard_id" integer NOT NULL
);

ALTER TABLE "market_global_settings" ADD FOREIGN KEY ("shard_id") REFERENCES "shards" ("id");

-- ZOOs Buildings

